// ============================================================================
//
// Copyright (C) 2006-2019 Talend Inc. - www.talend.com
//
// This source code is available under agreement available at
// %InstallDIR%\features\org.talend.rcp.branding.%PRODUCTNAME%\%PRODUCTNAME%license.txt
//
// You should have received a copy of the agreement
// along with this program; if not, write to Talend SA
// 9 rue Pages 92150 Suresnes, France
//
// ============================================================================
package routines;

/**
 * Empty routine entry to include library dependencies for generated DQ routines, such as "antlr" and
 * "dataquality.parser" library for routines generated by tStandardizeRow component.
 */
public class DataQualityDependencies {
    /**
     * intentionally left empty
     */
}
